[[zvk]]
=== Vector Cryptography Extensions

This chapter describes the vector cryptography extensions to the RISC-V ISA.

[[crypto_vector_introduction]]
==== Introduction

This chapter describes the RISC-V _vector_ cryptography extensions.
All instructions described here are based on the Vector registers.
The instructions are designed to be highly performant, with large
application and server-class cores being the main target.
<<crypto_scalar_instructions>> describes
cryptographic instructions for smaller cores which do not
implement the vector extension.

[[crypto_vector_audience]]
===== Intended Audience

Cryptography is a specialized subject, requiring people with many different
backgrounds to cooperate in its secure and efficient implementation.
Where possible, we have written this specification to be understandable by
all, though we recognize that the motivations and references to
algorithms or other specifications and standards may be unfamiliar to those
who are not domain experts.

This specification anticipates being read and acted on by various people
with different backgrounds.
We have tried to capture these backgrounds
here, with a brief explanation of what we expect them to know, and how
it relates to the specification.
We hope this aids people's understanding of which aspects of the specification
are particularly relevant to them, and which they may (safely!) ignore or
pass to a colleague.

Cryptographers and cryptographic software developers::
These are the people we expect to write code using the instructions
in this specification.
They should understand the motivations for the
instructions we include, and be familiar with most of the algorithms
and outside standards to which we refer.

Computer architects::
We do not expect architects to have a cryptography background.
We nonetheless expect architects to be able to examine our instructions
for implementation issues, understand how the instructions will be used
in context, and advise on how best to fit the functionality the
cryptographers want.

Digital design engineers & micro-architects::
These are the people who will implement the specification inside a
core. Again, no cryptography expertise is assumed, but we expect them to
interpret the specification and anticipate any hardware implementation
issues, e.g., where high-frequency design considerations apply, or where
latency/area tradeoffs exist etc.
In particular, they should be aware of the literature around efficiently
implementing AES and SM4 SBoxes in hardware.

Verification engineers::
These people are responsible for ensuring the correct implementation of the
extensions in hardware.
No cryptography background is assumed.
We expect them to identify interesting test cases from the
specification. An understanding of their real-world usage will help with this.

These are by no means the only people concerned with the specification,
but they are the ones we considered most while writing it.

[[crypto_vector_sail_specifications]]
===== Sail Specifications

RISC-V maintains a
link:https://github.com/riscv/sail-riscv[formal model]
of the ISA specification,
implemented in the Sail ISA specification language
cite:[sail].
Note that _Sail_ refers to the specification language itself,
and that there is a _model of RISC-V_, written using Sail.

It was our intention to include actual Sail code in this specification.
However, the Vector Crypto Sail model needs the Vector Sail model as a
basis on which to build. This Vector Cryptography extensions specification
was completed before there was an approved RISC-V Vector Sail Model.
Therefore, we don't have any Sail code to include in the instruction
descriptions. Instead we have included Sail-like pseudocode. While we have
endeavored to adhere to Sail syntax, we have taken some liberties for the
sake of simplicity where we believe that that our intent is clear to the
reader.

[NOTE]
====
Where variables are concatenated, the order shown is how they would appear
in a vector register from left to right.
For example, an element group specified as `{a, b, e, f}` would appear in a vector
register with `a` having the highest element index of the group and `f` having the
lowest index of the group.
====

For the sake of brevity, our pseudocode does not include the handling of
masks or tail elements. We follow the _undisturbed_ and _agnostic_ policies
for masks and tails as described in <<sec-agnostic>>. Furthermore, the code does not explicitly handle overlap and SEW
constraints; these are, however, explicitly stated in the text.

In many cases the pseudocode includes
calls to supporting functions which are too verbose to include directly
in the specification.
This supporting code is listed in
<<crypto_vector_appx_sail>>.


The
link:https://alasdair.github.io/manual.html[Sail Manual]
is recommended reading in order to best understand the code snippets.
Also,
link:https://github.com/billmcspadden-riscv/sail/blob/cookbook_br/cookbook/doc/TheSailCookbook_Complete.pdf[The Sail Programming Language: A Sail Cookbook]
is a good reference.

For the latest RISC-V Sail model, refer to
the formal model GitHub
link:https://github.com/riscv/sail-riscv[repository].

[[crypto_vector_policies]]
===== Policies

In creating this extension, we tried to adhere to the following
policies:

* Where there is a choice between:
  1) supporting diverse implementation strategies for an algorithm
  or
  2) supporting a single implementation style which is more performant /
     less expensive;
  the vector crypto extensions will pick the more constrained but performant
  option.
  This fits a common pattern in other parts of the RISC-V specifications,
  where recommended (but not required) instruction sequences for performing
  particular tasks are given as an example, such that both hardware and
  software implementers can optimize for only a single use-case.

* The extensions will be designed to support _existing_ standardized
  cryptographic constructs well.
  It will not try to support proposed standards, or cryptographic
  constructs which exist only in academia.
  Cryptographic standards which are settled upon concurrently with or after
  the RISC-V vector cryptographic extensions standardization will be dealt with
  by future RISC-V vector cryptographic
  standard extensions.

* Historically, there has been some discussion
  cite:[LSYRR:04]
  on how newly supported operations in general-purpose computing might
  enable new bases for cryptographic algorithms.
  The standard will not try to anticipate new useful low-level
  operations which _may_ be useful as building blocks for
  future cryptographic constructs.

* Regarding side-channel countermeasures:
  Where relevant, proposed instructions must aim to remove the
  possibility of any timing side-channels. All instructions
  shall be implemented with data-independent timing. That is, the latency of
  the execution of these instructions shall not vary with different input values.

[[crypto-vector-element-groups]]
===== Element Groups

Many vector crypto instructions operate on operands that are wider than elements (which are currently limited
to 64 bits wide).
Typically, these operands are 128 and 256 bits wide. In many cases, these operands are comprised of smaller
operands that are combined (for example, each SHA-2 operand is comprised of 4 words). However, in other cases
these operands are a single value (for example, in the AES round instructions, each operand is 128-bit block
or round key).

We treat these operands as a vector of one or more _element groups_ as defined in <<vector-element-groups>>.

Each vector crypto instruction that operates on element groups explicitly specifies their three defining
parameters: EGW, EGS, and EEW.

[%autowidth]
[%header,cols="4,4,4,4,4"]
|===
| Instruction Group
| Extension
| EGW
| EEW
| EGS

| AES      | extlink:zvkned[]     | 128 | 32 | 4
| SHA256   | extlink:zvknha[]     | 128 | 32 | 4
| SHA512   | extlink:zvknhb[]     | 256 | 64 | 4
| GCM      | extlink:zvkg[]       | 128 | 32 | 4
| SM4      | extlink:zvksed[]     | 128 | 32 | 4
| SM3      | extlink:zvksh[]      | 256 | 32 | 8
|===

[NOTE]
====
- Element Group Width (EGW) - total number of bits in an element group
- Effective Element Width (EEW) - number of bits in each element
- Element Group Size (EGS) - number of elements in an element group
====

[[norm:veccrypto_eeweqsew]]
For all of the vector crypto instructions in this specification, EEW=SEW.

[NOTE]
====
The required SEW for each cryptographic instruction was chosen to match what is
typically needed for other instructions when implementing the targeted algorithm.
====

- A *Vector Element Group* is a vector of one or more element groups.
- A *Scalar Element Group* is a single element group.

Element groups can be formed across registers in implementations where
VLEN<EGW by using an LMUL>1.

[NOTE]
====
Since the ext:v[] extension requires a minimum of VLEN of 128,
at most such implementations would require LMUL=2 to form the largest element groups in this specification.

However, implementations with a smaller VLEN, such as embedded designs, will requires a larger LMUL
to form the necessary element groups.
It is important to keep in mind that this reduces the number of register groups available such
that it may be difficult or impossible to write efficient code for the intended cryptographic algorithms.

For example, an implementation with VLEN=32 would need to set LMUL=8 to create a
256-bit element group for SM3. This would mean that there would only be 4 register groups,
3 of which would be consumed by a single SM3 message-expansion instruction.
====

As with all vector instructions, the number of elements processed is specified by the
vector length csr:vl[]. The number of element groups operated upon is then csr:vl[]/EGS.
Likewise the starting element group is csr:vstart[]/EGS.
See <<crypto-vector-instruction-constraints>> for limitations on csr:vl[] and csr:vstart[]
for vector crypto instructions.

// If this ratio is not an integer for a vector crypto instruction, an illegal-instruction exception is raised.

// Since `vstart` is expressed in elements, the starting element group is `vstart`/`EGS`.
// If this ratio is not an integer for a vector crypto instruction, an illegal-instruction exception is raised.

[[crypto-vector-instruction-constraints]]
===== Instruction Constraints

All standard vector instruction constraints specified by the ext:v[] extension apply to Vector Crypto instructions.
In addition to those constraints a few additional specific constraints are introduced.

The following is a quick reference for the various constraints of specific Vector Crypto instructions.


csr:vl[] and csr:vstart[] constraints::
[#norm:veccrypto_vl_vstart_egsconstr]#Since csr:vl[] and csr:vstart[] refer to elements, Vector Crypto instructions that use elements groups
(See <<crypto-vector-element-groups>>) require that these values are an integer multiple of the
Element Group Size (EGS).#

- [#norm:veccrypto_vl_vstart_rsv]#Instructions that violate the csr:vl[] or csr:vstart[] requirements are _reserved_.#

[%autowidth]
[%header,cols="4,4"]
|===
| Instructions
| EGS

| insn:vaes*[]   | 4
| insn:vsha2*[]  | 4
| insn:vg*[]     | 4
| insn:vsm3*[]   | 8
| insn:vsm4*[]   | 4

|===

LMUL constraints::
[#norm:veccrypto_lmul_egwconstr]#For element-group instructions, LMUL{times}VLEN must always be at least as large as EGW, otherwise an
_illegal-instruction exception_ is raised, even if csr:vl[]=0.#

[%autowidth]
[%header,cols="4,2,2"]
|===
| Instructions
| SEW
| EGW

| insn:vaes*[]   | 32 | 128
| insn:vsha2*[]  | 32 | 128
| insn:vsha2*[]  | 64 | 256
| insn:vg*[]     | 32 | 128
| insn:vsm3*[]   | 32 | 256
| insn:vsm4*[]   | 32 | 128

|===


SEW constraints::
[#norm:veccrypto_sew_rsv]#Some Vector Crypto instructions are only defined for a specific SEW. In such a case
all other SEW values are _reserved_.#

[%autowidth]
[%header,cols="4,4"]
|===
| Instructions
| Required SEW

| insn:vaes*[]          | 32
| Zvknha: insn:vsha2*[] | 32
| Zvknhb: insn:vsha2*[] | 32 or 64
| insn:vg*[]            | 32
| insn:vsm3*[]          | 32
| insn:vsm4*[]          | 32


|===

Vector/Scalar constraints::
This specification defines new vector/scalar (insn:*.vs[]) instructions that uses *Scalar Element Groups*. The *Scalar Element Group* operand has EMUL = ceil(EGW / VLEN).

[NOTE]
====
Scalar element group operands do not need to be aligned to LMUL for any implementation with VLEN >= EGW.
====

[#norm:veccrypto_vsins_vs2]#In the case of the insn:*.vs[] instructions defined in this specification, _vs2_ holds a 128-bit scalar element group.#
[#norm:veccrypto_vsins_vdvs2overlap]#For implementations with VLEN ≥ 128, _vs2_ refers to a single register. Thus, the _vd_ register group must not
overlap the _vs2_ register.
However, in implementations where VLEN < 128, _vs2_ refers to a register group comprised of the number
of registers needed to hold the 128-bit scalar element group. In this case, the _vd_ register group must not
overlap this _vs2_ register group.#

[%autowidth]
[%header,cols="4,4,4"]
|===
| Instruction
| Register
| Cannot Overlap

| insn:vaes*.vs[]      | vs2      | vd
| insn:vsm4r.vs[]      | vs2      | vd
| insn:vsha2c*[]       | vs1, vs2 | vd
| insn:vsha2ms[]       | vs1, vs2 | vd
| insn:vsm3me[]        | vs2      | vd
| insn:vsm3c[]         | vs2      | vd


|===

[[crypto-vector-scalar-instructions]]
===== Vector-Scalar Instructions

The RISC-V Vector Extension defines three encodings for Vector-Scalar operations which get their scalar operand from a GPR or FP register:

- OPIVX: Scalar GPR _x_ register
- OPFVF: Scalar FP _f_ register
- OPMVX: Scalar GPR _x_ register

However, the Vector Extensions include Vector Reduction Operations which can also be considered
Vector-Scalar operations because a scalar operand is provided from element 0 of
vector register _vs1_. The vector operand is provided in vector register group _vs2_.
These reduction operations all use the insn:*.vs[] suffix in their mnemonics. Additionally, the reduction operations all produce a scalar result in element 0 of the destination register, _vd_.

The Vector Crypto Extensions define Vector-Scalar instructions that are similar to these
Vector Reduction Operations in that they get a scalar operand from a vector register. However, they differ
in that they get a scalar element group
(see <<crypto-vector-element-groups>>)
from _vs2_ and [#norm:veccrypto_vsins_vd]#they return _vector_ results to _vd_, which is also a source vector operand.#
These Vector-Scalar crypto instructions also use the insn:*.vs[] suffix in their mnemonics.

[NOTE]
====
We chose to use _vs2_ as the scalar operand, and _vd_ as the vector operand, so that we could use the _vs1_
specifier as additional encoding bits for these instructions. This allows these instructions to have a
much smaller encoding footprint, leaving more room for other instructions in the future.
====

[#norm:veccrypto_vsins_vs2function]#These instructions enable a single key, specified as a scalar element group in _vs2_, to be
applied to each element group of register group _vd_.#

[NOTE]
====
Scalar element groups will occupy at most a single register in application processors. However, in implementations where
VLEN<128, they will occupy 2 (VLEN=64) or 4 (VLEN=32) registers.
====


[NOTE]
====
It is common for multiple AES encryption rounds (for example) to be performed in parallel with the same
round key (e.g. in counter modes).
Rather than having to first splat the common key across the whole vector group, these vector-scalar
crypto instructions allow the round key to be specified as a scalar element group.
====

// In the case of AES256 all-rounds instructions we need to provide two 128-bit keys; one is held in `vs1` and
// the other is held in `vs2`. The 128-bit data to be processed is held in `vd`.
// A vector-scalar form of this instruction looks different from the existing vector-scalar instructions in that
// both `vs1` and `vs2` are treated as scalar operands that apply to the vector operands of `vd`.

// [NOTE]
// ====
// Previously, the AES and SM4 instructions that performed rounds operations (including AES all-rounds instructions)
// were defined to be destructive operations where the data source was provided in `vd` and the key was provided in
// `vs2`. With the advent of the new crypto vector-scalar instructions, we are changing these instructions
// to use `vs1` for the key and `vs2` for the data.
// In the case of vector-scalar instructions, the scalar key will be held in
// element group 0 of `vs1` . This is done to remain consistent with the use of `vs1` for the scalar element in
// all of the existing vector-scalar operations as well as the vector reduction operations.
// ====

[[crypto-vector-software-portability]]
===== Software Portability
The following contains some guidelines that enable the portability of vector-crypto-based code
to implementations with different values for VLEN.

Application Processors::
Application processors are expected to follow the ext:v[] extension and will therefore have VLEN{ge}128.



// [NOTE]
// ====
Since most of the _cryptography-specific_ instructions have an EGW=128, nothing special needs to be done
for these instructions to support implementations with VLEN=128.

However, the SHA-512 and SM3 instructions have an EGW=256. Implementations with VLEN=128, require that
LMUL is doubled for these instructions in order to create 256-bit elements across a pair of registers.
Code written with this doubling of LMUL will not affect the results returned by implementations with VLEN{ge}256
because csr:vl[] controls how many element groups are processed. Therefore, we recommend that libraries that implement
SHA-512 and SM3 employ this doubling of LMUL to ensure that the software can run on all implementation
with VLEN{ge}128.

While the doubling of LMUL for these instructions is _safe_ for implementations with VLEN{ge}256, it may be less
optimal as it will result in unnecessary register pressure and might exact a performance penalty in
some microarchitectures. Therefore, we suggest that in addition to providing portable code for SHA-512 and SM3,
libraries should also include more optimal code for these instructions when VLEN{ge}256.
// ====

[%autowidth]
[%header,cols="4,4,4,4"]
|===
| Algorithm
| Instructions
| VLEN
| LMUL

| SHA-512 | insn:vsha2*[] | 64 | csr:vl[]/2
| SM3     | insn:vsm3*[]  | 32 | csr:vl[]/4
|===

// [NOTE]
// ====
// We recommend that all library code for application processors be written so that it can be run on any
// implementation with `VLEN` {ge} 128. Such libraries are also encouraged to have versions of code for
// SHA-512 and SM3 optimized for implementations with `VLEN` {ge} 256.
// ====

Embedded Processors::

Embedded processors will typically have implementations with VLEN<128. This will require code to be written with
larger LMUL values to enable the element groups to be formed.

The insn:*.vs[] instructions require scalar element groups of EGW=128. On implementations with VLEN<128, these scalar
element groups will necessarily be formed across registers. This is different from most scalars in vector instructions
that typically consume part of a single register.


// [NOTE]
// ====
We recommend that different code be available for VLEN=32 and VLEN=64, as code written for VLEN=32 will
likely be too burdensome for VLEN=64 implementations.
// ====

[[crypto_vector_extensions]]
==== Extensions Overview

The section introduces all of the  extensions in the Vector Cryptography
Instruction Set Extension Specification.

[#norm:Zvknhb_Zvkn_Zvknc_Zvkng_depZve64x]#The extlink:zvknhb[], extlink:zvkn[], extlink:zvknc[], extlink:zvkng[], and extlink:zvksc[] depend on ext:zve64x[].#

[#norm:Zvkb_Zvkg_Zvkned_Zvknha_Zvksed_Zvksh_Zvks_Zvksc_Zvksg_Zvkt_depZve32x]#All of the other Vector Crypto Extensions depend on ext:zve32x[].#

[#norm:Zvknhb_impZvknha]#ext:zvknhb[] implies ext:zvknha[].#

Note: If ext:zve32x[] is supported then ext:zvkb[] provides support for EEW of 8, 16, and 32. If ext:zve64x[] is supported then ext:zvkb[] also adds support for EEW 64.


// See <<crypto-vector-element-groups>> for more details on vector element groups and the drawbacks of
// small `VLEN` values.


All _cryptography-specific_ instructions defined in this Vector Crypto specification (i.e., those
in extlink:zvkned[], extlink:zvknha[], extlink:zvknhb[], extlink:zvkg[], extlink:zvksed[] and extlink:zvksh[] but _not_ extlink:zvkb[]) shall
be executed with data-independent execution latency as defined in the
<<#crypto_scalar_instructions,RISC-V Scalar Cryptography Extensions specification>>.
[#norm:veccrypto_indepZkt]#It is important to note that the Vector Crypto instructions are independent of the
implementation of the ext:zkt[] extension and do not require that ext:zkt[] is implemented.#

This specification includes a extlink:zvkt[] extension that, when implemented, requires certain vector instructions
(including extlink:zvkb[]) to be executed with data-independent execution latency.

Detection of individual cryptography extensions uses the
unified software-based RISC-V discovery method.

[NOTE]
====
At the time of writing, these discovery mechanisms are still a work in
progress.
====

[[ext:zvkb]]
===== ext:zvkb[] Vector Cryptography Bit-manipulation

Vector bit-manipulation instructions that are essential
for implementing common cryptographic workloads securely and
efficiently.

[NOTE]
====
This ext:zvkb[] extension is a proper subset of the ext:zvbb[] extension.
ext:zvkb[] allows for vector crypto implementations without incurring
the cost of implementing the additional bitmanip instructions
in the ext:zvbb[] extension: insn:vbrev.v[], insn:vclz.v[], insn:vctz.v[],
insn:vcpop.v[], insn:vwsll.vv[], insn:vwsll.vx[], and insn:vwsll.vi[].
====

[%autowidth]
[%header,cols="2,4"]
|===
|Mnemonic
|Instruction

| insn:vandn.*[]   | <<insns-vandn>>
| insn:vbrev8.v*[] | <<insns-vbrev8>>
| insn:vrev8.v*[]  | <<insns-vrev8>>
| insn:vrol.*[]    | <<insns-vrol>>
| insn:vror.*[]    | <<insns-vror>>
|===

<<<

[[ext:zvkg]]
===== ext:zvkg[] Vector GCM/GMAC

Instructions to enable the efficient implementation of GHASH~H~ which is used in Galois/Counter Mode (GCM) and
Galois Message Authentication Code (GMAC).

[#norm:Zvkg_egw128b_elem32b]#All of these instructions work on 128-bit element groups comprised of four 32-bit elements.#

GHASH~H~ is defined in the
// link:https://csrc.nist.gov/publications/detail/sp/800-38d/final[NIST Special Publication 800-38D]
 "`Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC`"
 cite:[nist:gcm]
(NIST Specification).

[NOTE]
====
GCM is used in conjunction with block ciphers (e.g., AES and SM4) to encrypt a message and
provide authentication.
GMAC is used to provide authentication of a message without encryption.
====

[#norm:Zvkg_dataindeptiming]#To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.#

[#norm:Zvkg_vl]#The number of element groups to be processed is csr:vl[]/EGS.
csr:vl[] must be set to the number of SEW=32 elements to be processed and
therefore must be a multiple of EGS=4.#
[#norm:Zvkg_vstart]#Likewise, csr:vstart[] must be a multiple of EGS=4.#

[%autowidth]
[%header,cols="^2,4,4,4"]
|===

|SEW
|EGW
|Mnemonic
|Instruction
| 32 | 128 | insn:vghsh.vv[] | <<insns-vghsh>>
| 32 | 128 | insn:vgmul.vv[] | <<insns-vgmul>>

|===

<<<

[[ext:zvkned]]
===== ext:zvkned[] NIST Suite: Vector AES Block Cipher

Instructions for accelerating
encryption, decryption and key-schedule
functions of the AES block cipher as defined in
Federal Information Processing Standards Publication 197
cite:[nist:fips:197]

[#norm:Zvkned_egw128b_elem32b]#All of these instructions work on 128-bit element groups comprised of four
32-bit elements.#

For the best performance, it is suggested that these instruction be implemented on systems with VLEN>=128.
On systems with VLEN<128, element groups may be formed by concatenating 32-bit elements
from two or four registers by using an LMUL=2 and LMUL=4 respectively.

// Implementations with `VLEN<128` should consider the existing
// Scalar Cryptography Extensions, specifically extlink:zkne[] and extlink:zknd[]
// for accelerated cryptographic operations.

[#norm:Zvkned_dataindeptiming]#To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.#

[#norm:Zvkned_vl]#The number of element groups to be processed is csr:vl[]/EGS.
csr:vl[] must be set to the number of SEW=32 elements to be processed and
therefore must be a multiple of EGS=4.#
[#norm:Zvkned_vstart]#Likewise, csr:vstart[] must be a multiple of EGS=4.#

[%autowidth]
[%header,cols="^2,4,4,4"]
|===
|SEW
|EGW
|Mnemonic
|Instruction

| 32| 128 | insn:vaesef.*[]   | <<insns-vaesef>>
| 32| 128 | insn:vaesem.*[]   | <<insns-vaesem>>
| 32| 128 | insn:vaesdf.*[]   | <<insns-vaesdf>>
| 32| 128 | insn:vaesdm.*[]   | <<insns-vaesdm>>
| 32| 128 | insn:vaeskf1.vi[] | <<insns-vaeskf1>>
| 32| 128 | insn:vaeskf2.vi[] | <<insns-vaeskf2>>
| 32| 128 | insn:vaesz.vs[]   | <<insns-vaesz>>
|===

<<<

[[ext:zvknha]]
===== ext:zvknha[] and ext:zvknhb[] NIST Suite: Vector SHA-2 Secure Hash

[[ext:zvknhb]]
Instructions for accelerating SHA-2 as defined in FIPS PUB 180-4 Secure Hash Standard (SHS)
cite:[nist:fips:180:4]

SEW differentiates between SHA-256 (SEW=32) and SHA-512 (SEW=64).

- [#norm:Zvknha_Zvknhb_sha256_egw128b_elem32b]#SHA-256: these instructions work on 128-bit element groups comprised of four 32-bit elements.#
- [#norm:Zvknhb_sha512_egw256b_elem64b]#SHA-512: these instructions work on 256-bit element groups comprised of four 64-bit elements.#

[%autowidth]
[%header,cols="^2,^2,^2,2"]
|===
|SEW
|EGW
|SHA-2
|Extension

|32 | 128 | SHA-256 | ext:zvknha[], ext:zvknhb[]
|64 | 256 | SHA-512 | ext:zvknhb[]
|===

// link:https://doi.org/10.6028/NIST.FIPS.180-4[FIPS PUB 180-4 Secure Hash Standard (SHS)])

- [#norm:Zvknhb_sha256_sha512]#ext:zvknhb[] supports SHA-256 and SHA-512.#
- [#norm:Zvknha_sha256]#ext:zvknha[] supports only SHA-256.#

// [NOTE]
// ====
// Zvknhb is implemented, `SEW` is used to differentiate between SHA-256 (SEW=32) and SHA-512 (SEW=64).
// If Zvknha is implemented, only SHA-256 is supported, and SEW must be 32.
// ====

SHA-256 implementations with VLEN<128 require LMUL>1 to combine
32-bit elements from register groups to provide all four elements of the element group.

SHA-512 implementations with VLEN<256 require LMUL>1 to combine
64-bit elements from register groups to provide all four elements of the element group.

// SHA-2 is defined in
// link:https://doi.org/10.6028/NIST.FIPS.180-4[FIPS PUB 180-4 Secure Hash Standard (SHS)].

[#norm:Zvknha_Zvknhb_dataindeptiming]#To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.#

// [NOTE]
// ====
// It is recommended that implementations have VLEN{ge}128 for these instructions.
// // Furthermore, for the best performance in SHA512, it is recommended that implementations have VLEN{ge}256.
// When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the
// specified register groups can be combined to form the full element group.
// ====

[#norm:Zvknha_Zvknhb_vl]#The number of element groups to be processed is csr:vl[]/EGS.
csr:vl[] must be set to the number of SEW elements to be processed and
therefore must be a multiple of EGS=4.# +
[#norm:Zvknha_Zvknhb_vstart]#Likewise, csr:vstart[] must be a multiple of EGS=4.#

[%autowidth]
[%header,cols="2,4"]
|===
// |`VLENmin`
|Mnemonic
|Instruction

// | 128
| insn:vsha2ms.vv[]   | <<insns-vsha2ms>>
// | 128
| insn:vsha2c*.vv[]   | <<insns-vsha2c>>
|===

<<<

[[ext:zvksed]]
===== ext:zvksed[] ShangMi Suite: SM4 Block Cipher

Instructions for accelerating
encryption, decryption, and key-schedule
functions of the SM4 block cipher.

The SM4 block cipher is specified in _32907-2016: \{SM4} Block Cipher Algorithm_
cite:[gbt:sm4]

There are other various sources available that describe the SM4 block cipher.
While not the final version of the standard,
link:https://www.rfc-editor.org/rfc/rfc8998.html[RFC 8998 ShangMi (SM) Cipher Suites for TLS 1.3]
is useful and easy to access.

// https://datatracker.ietf.org/doc/id/draft-crypto-sm4-00

[#norm:Zvksed_egw128b_elem32b]#All of these instructions work on 128-bit element groups comprised of four
32-bit elements.#

// Systems which implement VLEN<128 should consider the existing
// Scalar Cryptography Extensions, specifically extlink:zkne[] and extlink:zknd[]
// for accelerated cryptographic operations.

[#norm:Zvksed_dataindeptiming]#To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.#

[#norm:Zvksed_vl]#The number of element groups to be processed is csr:vl[]/EGS.
csr:vl[] must be set to the number of SEW=32 elements to be processed and
therefore must be a multiple of EGS=4.# +
[#norm:Zvksed_vstart]#Likewise, csr:vstart[] must be a multiple of EGS=4.#

[%autowidth]
[%header,cols="^2,4,4,4"]
|===
|SEW
|EGW
|Mnemonic
|Instruction

| 32 | 128 | insn:vsm4k.vi[]  | <<insns-vsm4k>>
| 32 | 128 | insn:vsm4r.*[]   | <<insns-vsm4r>>
|===

<<<

[[ext:zvksh]]
===== ext:zvksh[] ShangMi Suite: SM3 Secure Hash

Instructions for accelerating
functions of the SM3 Hash Function.

The SM3 secure hash algorithm is specified in _32905-2016: SM3 Cryptographic Hash Algorithm_
cite:[gbt:sm3]

There are other various sources available that describe the SM3 secure hash.
While not the final version of the standard,
link:https://www.rfc-editor.org/rfc/rfc8998.html[RFC 8998 ShangMi (SM) Cipher Suites for TLS 1.3]
is useful and easy to access.

// https://datatracker.ietf.org/doc/id/draft-crypto-sm4-00

[#norm:Zvksh_egw256b_elem32b]#All of these instructions work on 256-bit element groups comprised of
eight 32-bit elements.#

Implementations with VLEN<256 require LMUL>1 to combine 32-bit elements from register groups
to provide all eight elements of the element group.

// The instructions will be most efficient on implementations where `VLEN`{ge}256.
// They will also provide substantial benefit on implementations where
// `VLEN`=128, but will require an `LMUL`>1 in order to combine elements
// within a register group to form the full element group.
// Implementations with `VLEN`<128 might not be as efficient and should
// consider the existing
// Scalar Cryptography Extensions, specifically `Zkne` and `Zknd`,
// for accelerated cryptographic operations.

[#norm:Zvksh_dataindeptiming]#To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.#

[#norm:Zvksh_vl]#The number of element groups to be processed is csr:vl[]/EGS.
csr:vl[] must be set to the number of SEW=32 elements to be processed and
therefore must be a multiple of EGS=8.# +
[#norm:Zvksh_vstart]#Likewise, csr:vstart[] must be a multiple of EGS=8.#

[%autowidth]
[%header,cols="2,4,4,4"]
|===
| SEW
| EGW
| Mnemonic
| Instruction

| 32 | 256 | insn:vsm3me.vv[] | <<insns-vsm3me>>
| 32 | 256 | insn:vsm3c.vi[]  | <<insns-vsm3c>>
|===

<<<

[[ext:zvkn]]
===== ext:zvkn[] NIST Algorithm Suite

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvkned[]  | extlink:zvkned[]
| ext:zvknhb[]  | extlink:zvknhb[]
| ext:zvkb[]    | extlink:zvkb[]
| ext:zvkt[]    | extlink:zvkt[]
|===

[NOTE]
====
While ext:zvkg[] and ext:zvbc[] are not part of this extension, it is recommended that at least one of them is implemented with this extension to enable efficient AES-GCM.
====

<<<

[[ext:zvknc]]
===== ext:zvknc[] NIST Algorithm Suite with carry-less multiply

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvkn[]  | extlink:zvkn[]
| ext:zvbc[]  | extlink:zvbc[]
|===

[NOTE]
====
This extension combines the NIST Algorithm Suite with the
vector carry-less multiply extension to enable AES-GCM.
====

<<<

[[ext:zvkng]]
===== ext:zvkng[] NIST Algorithm Suite with GCM

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvkn[]  | extlink:zvkn[]
| ext:zvkg[]  | extlink:zvkg[]
|===

[NOTE]
====
This extension combines the NIST Algorithm Suite with the
GCM/GMAC extension to enable high-performance AES-GCM.
====

<<<

[[ext:zvks]]
===== ext:zvks[] ShangMi Algorithm Suite

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvksed[]  | extlink:zvksed[]
| ext:zvksh[]   | extlink:zvksh[]
| ext:zvkb[]    | extlink:zvkb[]
| ext:zvkt[]    | extlink:zvkt[]
|===

[NOTE]
====
While ext:zvkg[] and ext:zvbc[] are not part of this extension, it is recommended that at least one of them is implemented with this extension to enable efficient SM4-GCM.
====

<<<

[[ext:zvksc]]
===== ext:zvksc[] ShangMi Algorithm Suite with carry-less multiplication

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvks[]  | extlink:zvks[]
| ext:zvbc[]  | extlink:zvbc[]
|===

[NOTE]
====
This extension combines the ShangMi Algorithm Suite with the
vector carry-less multiply extension to enable SM4-GCM.
====

<<<

[[ext:zvksg]]
===== ext:zvksg[] ShangMi Algorithm Suite with GCM

This extension is shorthand for the following set of other extensions:

[%autowidth]
[%header,cols="^2,4"]
|===
|Included Extension
|Description


| ext:zvks[]  | extlink:zvks[]
| ext:zvkg[]  | extlink:zvkg[]
|===

[NOTE]
====
This extension combines the ShangMi Algorithm Suite with the
GCM/GMAC extension to enable high-performance SM4-GCM.
====

<<<

[[ext:zvkt]]
===== ext:zvkt[] Vector Data-Independent Execution Latency

The Zvkt extension requires all implemented instructions from the following list to be
executed with data-independent execution latency as defined in the
<<#crypto_scalar_instructions,RISC-V Scalar Cryptography Extensions specification>>.

Data-independent execution latency (DIEL) applies to all _data operands_ of an instruction, even those that are not a
part of the body or that are inactive. However, DIEL does not apply
to other values such as csr:vl[], csr:vtype[], and the mask (when used to control
execution of a masked vector instruction).
Also, DIEL does not apply to constant values specified in the
instruction encoding such as the use of the zero register (`x0`), and, in the
case of immediate forms of an instruction, the values in the immediate
fields (i.e., _imm_ and _uimm_).

In some cases--which are explicitly specified in the lists below--operands that are used as control rather than data
are exempt from DIEL.

[NOTE]
====
DIEL helps protect against side-channel timing attacks that are used
to determine data values that are intended to be kept secret. Such
values include cryptographic keys, plain text, and partially encrypted
text. DIEL is not intended to keep software (and cryptographic
algorithms contained therein) secret as it is assumed that an adversary
would already know these. This is why DIEL doesn't apply to constants
embedded in instruction encodings.

It is important that the _values_ of elements that are not in the body or that are masked off do not affect the execution
latency of the instruction. Sometimes such elements contain data that
also needs to be kept secret.
====

====== All extlink:zvbb[]  instructions
- insn:vandn.vv[]
- insn:vandn.vx[]
- insn:vclz.v[]
- insn:vcpop.v[]
- insn:vctz.v[]
- insn:vbrev.v[]
- insn:vbrev8.v[]
- insn:vrev8.v[]
- insn:vrol.vv[]
- insn:vrol.vx[]
- insn:vror.vv[]
- insn:vror.vx[]
- insn:vror.vi[]
- insn:vwsll.vv[]
- insn:vwsll.vx[]
- insn:vwsll.vi[]

[NOTE]
====
All extlink:zvkb[] instructions are also covered by DIEL as they are a
proper subset of extlink:zvbb[]
====

====== All extlink:zvbc[] instructions
- insn:vclmul.vv[]
- insn:vclmul.vx[]
- insn:vclmulh.vv[]
- insn:vclmulh.vx[]


====== add/sub
- insn:vsub.vv[]
- insn:vsub.vx[]
- insn:vrsub.vi[]
- insn:vrsub.vx[]
- insn:vadd.vv[]
- insn:vadd.vx[]
- insn:vadd.vi[]
- insn:vsub.vv[]
- insn:vsub.vx[]
- insn:vwadd.vv[]
- insn:vwadd.vx[]
- insn:vwadd.wv[]
- insn:vwadd.wx[]
- insn:vwaddu.vv[]
- insn:vwaddu.vx[]
- insn:vwaddu.wv[]
- insn:vwaddu.wx[]
- insn:vwsub.vv[]
- insn:vwsub.vx[]
- insn:vwsub.wv[]
- insn:vwsub.wx[]
- insn:vwsubu.vv[]
- insn:vwsubu.vx[]
- insn:vwsubu.wv[]
- insn:vwsubu.wx[]

====== add/sub with carry
- insn:vadc.vvm[]
- insn:vadc.vxm[]
- insn:vadc.vim[]
- insn:vmadc.vv[]
- insn:vmadc.vx[]
- insn:vmadc.vi[]
- insn:vmadc.vvm[]
- insn:vmadc.vxm[]
- insn:vmadc.vim[]
- insn:vmsbc.vv[]
- insn:vmsbc.vx[]
- insn:vmsbc.vvm[]
- insn:vmsbc.vxm[]
- insn:vsbc.vvm[]
- insn:vsbc.vxm[]

====== compare and set
- insn:vmseq.vv[]
- insn:vmseq.vx[]
- insn:vmseq.vi[]
- insn:vmsgt.vx[]
- insn:vmsgt.vi[]
- insn:vmsgtu.vx[]
- insn:vmsgtu.vi[]
- insn:vmsle.vx[]
- insn:vmsle.vv[]
- insn:vmsle.vi[]
- insn:vmsleu.vx[]
- insn:vmsleu.vv[]
- insn:vmsleu.vi[]
- insn:vmslt.vx[]
- insn:vmslt.vv[]
- insn:vmsltu.vx[]
- insn:vmsltu.vv[]
- insn:vmsne.vv[]
- insn:vmsne.vx[]
- insn:vmsne.vi[]

====== copy
- insn:vmv.s.x[]
- insn:vmv.x.s[]
- insn:vmv.v.v[]
- insn:vmv.v.x[]
- insn:vmv.v.i[]
- insn:vmv1r.v[]
- insn:vmv2r.v[]
- insn:vmv4r.v[]
- insn:vmv8r.v[]

====== extend
- insn:vsext.vf2[]
- insn:vsext.vf4[]
- insn:vsext.vf8[]
- insn:vzext.vf2[]
- insn:vzext.vf4[]
- insn:vzext.vf8[]

====== logical
- insn:vand.vv[]
- insn:vand.vx[]
- insn:vand.vi[]
- insn:vmor.mm[]
- insn:vmnor.mm[]
- insn:vmand.mm[]
- insn:vmandn.mm[]
- insn:vmnand.mm[]
- insn:vmorn.mm[]
- insn:vmxor.mm[]
- insn:vmxnor.mm[]
- insn:vor.vv[]
- insn:vor.vx[]
- insn:vor.vi[]
- insn:vxor.vv[]
- insn:vxor.vx[]
- insn:vxor.vi[]

====== multiply
- insn:vmul.vv[]
- insn:vmul.vx[]
- insn:vmulh.vv[]
- insn:vmulh.vx[]
- insn:vmulhu.vv[]
- insn:vmulhu.vx[]
- insn:vmulhsu.vv[]
- insn:vmulhsu.vx[]
- insn:vwmul.vv[]
- insn:vwmul.vx[]
- insn:vwmulu.vv[]
- insn:vwmulu.vx[]
- insn:vwmulsu.vv[]
- insn:vwmulsu.vx[]

====== multiply-add
- insn:vmacc.vv[]
- insn:vmacc.vx[]
- insn:vmadd.vv[]
- insn:vmadd.vx[]
- insn:vnmsac.vv[]
- insn:vnmsac.vx[]
- insn:vnmsub.vv[]
- insn:vnmsub.vx[]
- insn:vwmacc.vv[]
- insn:vwmacc.vx[]
- insn:vwmaccu.vv[]
- insn:vwmaccu.vx[]
- insn:vwmaccsu.vv[]
- insn:vwmaccsu.vx[]
- insn:vwmaccus.vx[]

====== Integer Merge
- insn:vmerge.vvm[]
- insn:vmerge.vxm[]
- insn:vmerge.vim[]

====== permute
In the insn:*.vv[] and insn:*.xv[] forms of the insn:vrgather[] and insn:vrgatherei16[] instructions,
the values in _vs1_ and _rs1_ are used for control and therefore are exempt from DIEL.

- insn:vrgather.vv[]
- insn:vrgather.vx[]
- insn:vrgather.vi[]
- insn:vrgatherei16.vv[]

====== shift
// The values in _vs1_, _rs1_, _imm_ are used for control (i.e., shift amount) and are exempt from DIEL.

- insn:vnsra.wv[]
- insn:vnsra.wx[]
- insn:vnsra.wi[]
- insn:vnsrl.wv[]
- insn:vnsrl.wx[]
- insn:vnsrl.wi[]
- insn:vsll.vv[]
- insn:vsll.vx[]
- insn:vsll.vi[]
- insn:vsra.vv[]
- insn:vsra.vx[]
- insn:vsra.vi[]
- insn:vsrl.vv[]
- insn:vsrl.vx[]
- insn:vsrl.vi[]

====== slide
- insn:vslide1up.vx[]
- insn:vslide1down.vx[]
- insn:vfslide1up.vf[]
- insn:vfslide1down.vf[]

In the insn:vslideup.vx[] and insn:vslidedown.vx[] instructions, the value in _rs1_
is used for control (i.e., slide amount) and therefore is exempt
from DIEL.

- insn:vslideup.vx[]
- insn:vslideup.vi[]
- insn:vslidedown.vx[]
- insn:vslidedown.vi[]

[NOTE]
====
The following instructions are not affected by ext:zvkt[]:

- *All storage operations*
- *All floating-point operations*
- add/sub saturate
* insn:vsadd.vv[]
* insn:vsadd.vx[]
* insn:vsadd.vi[]
* insn:vsaddu.vv[]
* insn:vsaddu.vx[]
* insn:vsaddu.vi[]
* insn:vssub.vv[]
* insn:vssub.vx[]
* insn:vssubu.vv[]
* insn:vssubu.vx[]
- clip
* insn:vnclip.wv[]
* insn:vnclip.wx[]
* insn:vnclip.wi[]
* insn:vnclipu.wv[]
* insn:vnclipu.wx[]
* insn:vnclipu.wi[]
- compress
* insn:vcompress.vm[]
- divide
* insn:vdiv.vv[]
* insn:vdiv.vx[]
* insn:vdivu.vv[]
* insn:vdivu.vx[]
* insn:vrem.vv[]
* insn:vrem.vx[]
* insn:vremu.vv[]
* insn:vremu.vx[]
- average
* insn:vaadd.vv[]
* insn:vaadd.vx[]
* insn:vaaddu.vv[]
* insn:vaaddu.vx[]
* insn:vasub.vv[]
* insn:vasub.vx[]
* insn:vasubu.vv[]
* insn:vasubu.vx[]
- mask Op
* insn:vcpop.m[]
* insn:vfirst.m[]
* insn:vid.v[]
* insn:viota.m[]
* insn:vmsbf.m[]
* insn:vmsif.m[]
* insn:vmsof.m[]
- min/max
* insn:vmax.vv[]
* insn:vmax.vx[]
* insn:vmaxu.vv[]
* insn:vmaxu.vx[]
* insn:vmin.vv[]
* insn:vmin.vx[]
* insn:vminu.vv[]
* insn:vminu.vx[]
- Multiply-saturate
* insn:vsmul.vv[]
* insn:vsmul.vx[]
- reduce
* insn:vredsum.vs[]
* insn:vwredsum.vs[]
* insn:vwredsumu.vs[]
* insn:vredand.vs[]
* insn:vredor.vs[]
* insn:vredxor.vs[]
* insn:vredmax.vs[]
* insn:vredmaxu.vs[]
* insn:vredmin.vs[]
* insn:vredminu.vs[]
- shift round
* insn:vssra.vv[]
* insn:vssra.vx[]
* insn:vssra.vi[]
* insn:vssrl.vv[]
* insn:vssrl.vx[]
* insn:vssrl.vi[]
- vset
* insn:vsetivli[]
* insn:vsetvl[]
* insn:vsetvli[]
====

[[crypto_vector_insns, reftext="Vector Cryptography Instructions"]]
==== Instructions

[[insns-vaesdf, Vector AES decrypt final round]]
===== insn:vaesdf.vv[] and insn:vaesdf.vs[]

Synopsis::
Vector AES final-round decryption

Mnemonic::
insn:vaesdf.vv[vd,vs2] +
insn:vaesdf.vs[vd,vs2]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00001'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESDF(_,_,_)",type=mapping,right]

where `VAESDF.OP = ZVK_VAESDF_VV` and
[source,sail]
----
include::sail:encdec_vaesdf[type=mapping,left-clause="ZVK_VAESDF_VV"]
----

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00001'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESDF(_,_,_)",type=mapping,right]

where `VAESDF.OP = ZVK_VAESDF_VS` and
[source,sail]
----
include::sail:encdec_vaesdf[type=mapping,left-clause="ZVK_VAESDF_VS"]
----

Reserved Encodings::
* SEW is any value other than 32
* Only for the insn:*.vs[] form: the _vd_ register group overlaps the _vs2_ scalar element group

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | round state
| _vs2_ | input  | 128  | 4 | 32 | round key
| _vd_  | output | 128  | 4 | 32 | new round state
|===

Description::
[[norm:vaesdf_final]] A final-round AES block cipher decryption is performed.

[#norm:vaesdf_ops]#The InvShiftRows and InvSubBytes steps are applied to each round state element group from _vd_.#
[#norm:vaesdf_xor_form]#This is then XORed with the round key in either the corresponding element group in _vs2_ (vector-vector
form) or scalar element group in _vs2_ (vector-scalar form).#

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.

//  if( ((vl%EGS)<>0) | ((vstart%EGS)<>0) | (LMUL*VLEN < EGW))  then {

Operation::
+
sail::execute[clause="VAESDF(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaesdm, Vector AES decrypt middle round]]
===== insn:vaesdm.vv[] and insn:vaesdm.vs[]

Synopsis::
Vector AES middle-round decryption

Mnemonic::
insn:vaesdm.vv[vd,vs2] +
insn:vaesdm.vs[vd,vs2]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESDM(_,_,_)",type=mapping,right]

where `VAESDM.OP = ZVK_VAESDM_VV` and
[source,sail]
----
include::sail:encdec_vaesdm[type=mapping,left-clause="ZVK_VAESDM_VV"]
----

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESDM(_,_,_)",type=mapping,right]

where `VAESDM.OP = ZVK_VAESDM_VS` and
[source,sail]
----
include::sail:encdec_vaesdm[type=mapping,left-clause="ZVK_VAESDM_VS"]
----

Reserved Encodings::
* SEW is any value other than 32
* Only for the insn:*.vs[] form: the _vd_ register group overlaps the _vs2_ scalar element group

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | round state
| _vs2_ | input  | 128  | 4 | 32 | round key
| _vd_  | output | 128  | 4 | 32 | new round state
|===

Description::
[[norm:vaesdm_mid]] A middle-round AES block cipher decryption is performed.

[#norm:vaesdm_ops]#The InvShiftRows and InvSubBytes steps are applied to each round state element group from _vd_.#
[#norm:vaesdm_xor_form]#This is then XORed with the round key in either the corresponding element group in _vs2_ (vector-vector
form) or the scalar element group in _vs2_ (vector-scalar form).# The result is then applied to the
[#norm:vaesdm_invmix]#InvMixColumns step.#

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.
//
// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
+
sail::execute[clause="VAESDM(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaesef, Vector AES encrypt final round]]
===== insn:vaesef.vv[] and insn:vaesef.vs[]

Synopsis::
Vector AES final-round encryption

Mnemonic::
insn:vaesef.vv[vd,vs2] +
insn:vaesef.vs[vd,vs2]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00011'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESEF(_,_,_)",type=mapping,right]

where `VAESEF.OP = ZVK_VAESEF_VV` and
[source,sail]
----
include::sail:encdec_vaesef[type=mapping,left-clause="ZVK_VAESEF_VV"]
----

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00011'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESEF(_,_,_)",type=mapping,right]

where `VAESEF.OP = ZVK_VAESEF_VS` and
[source,sail]
----
include::sail:encdec_vaesef[type=mapping,left-clause="ZVK_VAESEF_VS"]
----

Reserved Encodings::
* SEW is any value other than 32
* Only for the insn:*.vs[] form: the _vd_ register group overlaps the _vs2_ scalar element group

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | round state
| _vs2_ | input  | 128  | 4 | 32 | round key
| _vd_  | output | 128  | 4 | 32 | new round state
|===

Description::
[[norm:vaesef_final]] A final-round encryption function of the AES block cipher is performed.

[#norm:vaesef_ops]#The SubBytes and ShiftRows steps are applied to each round state element group from _vd_.#
[#norm:vaesef_xor_form]#This is then XORed with the round key in either the corresponding element group in _vs2_ (vector-vector
form) or the scalar element group in _vs2_ (vector-scalar form).#

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.
//
// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.


Operation::
+
sail::execute[clause="VAESEF(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaesem, Vector AES encrypt middle round]]
===== insn:vaesem.vv[] and insn:vaesem.vs[]

Synopsis::
Vector AES middle-round encryption

Mnemonic::
insn:vaesem.vv[vd,vs2] +
insn:vaesem.vs[vd,vs2]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00010'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESEM(_,_,_)",type=mapping,right]

where `VAESEM.OP = ZVK_VAESEM_VV` and
[source,sail]
----
include::sail:encdec_vaesem[type=mapping,left-clause="ZVK_VAESEM_VV"]
----

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00010'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESEM(_,_,_)",type=mapping,right]

where `VAESEM.OP = ZVK_VAESEM_VS` and
[source,sail]
----
include::sail:encdec_vaesem[type=mapping,left-clause="ZVK_VAESEM_VS"]
----

Reserved Encodings::
* SEW is any value other than 32
* Only for the insn:*.vs[] form: the _vd_ register group overlaps the _vs2_ scalar element group


Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | round state
| _vs2_ | input  | 128  | 4 | 32 | Round key
| _vd_  | output | 128  | 4 | 32 | new round state
|===

Description::
[[norm:vaesem_mid]] A middle-round encryption function of the AES block cipher is performed.

[#norm:vaesem_ops]#The SubBytes, ShiftRows, and MixColumns steps are applied to each round state element group from _vd_.#
[#norm:vaesem_xor_form]#This is then XORed with the round key in either the corresponding element group in _vs2_ (vector-vector
form) or the scalar element group in _vs2_ (vector-scalar form).#

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.
//
// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
+
sail::execute[clause="VAESEM(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaeskf1, Vector AES-128 Forward KeySchedule]]
===== insn:vaeskf1.vi[]

Synopsis::
Vector AES-128 Forward KeySchedule generation

Mnemonic::
insn:vaeskf1.vi[vd,vs2,uimm]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '100010'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESKF1_VI(_,_,_)",type=mapping,right]

Reserved Encodings::
* SEW is any value other than 32

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _uimm_ | input  | -    | - | -  | Round Number (rnd)
| _vs2_  | input  | 128  | 4 | 32 | Current round key
| _vd_   | output | 128  | 4 | 32 | Next round key
|===

Description::
[#norm:vaeskf1_round]#A single round of the forward AES-128 KeySchedule is performed.#

// Within each element group,
[#norm:vaeskf1_wordgen]#The next round key is generated word by word from the
current round key element group in _vs2_ and the immediately previous word of the
round key.# The least significant word is generated using the most significant
word of the current round key as well as a round constant which is selected by
the round number.

The round number, which [#norm:vaeskf1_uimm_src]#ranges from 1 to 10, comes from _uimm[3:0]_;
_uimm[4]_ is ignored.#
[#norm:vaeskf1_uimm_map]#The out-of-range _uimm[3:0]_ values of 0 and 11{endash}15 are mapped to in-range
values by inverting _uimm[3]_.# Thus, 0 maps to 8, and 11{endash}15 maps to 3{endash}7.
The round number is used to specify a round constant which is used in generating
the first round key word.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.

[NOTE]
====
We chose to map out-of-range round numbers to in-range values as this allows the instruction's
behavior to be fully defined for all values of _uimm[4:0]_ with minimal extra logic.
====

// Each `EGW=128` element group next-round-key output is produced and is written to each `EGW=128`
// element group of `vd`.


//
// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.


Operation::
+
sail::execute[clause="VAESKF1_VI(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaeskf2, Vector AES-256 Forward KeySchedule]]
===== insn:vaeskf2.vi[]

Synopsis::
Vector AES-256 Forward KeySchedule generation

Mnemonic::
insn:vaeskf2.vi[vd,vs2,uimm]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101010'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESKF2_VI(_,_,_)",type=mapping,right]

Reserved Encodings::
* SEW is any value other than 32

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_   | input  | 128  | 4 | 32 | Previous Round key
| _uimm_ | input  | -    | - | -  | Round Number (rnd)
| _vs2_  | input  | 128  | 4 | 32 | Current Round key
| _vd_   | output | 128  | 4 | 32 | Next round key
|===

Description::
[#norm:vaeskf2_round]#A single round of the forward AES-256 KeySchedule is performed.#

// Within each element group,
[#norm:vaeskf2_wordgen]#The next round key is generated word by word from the
previous round key element group in _vd_ and the immediately previous word of the
round key.# The [#norm:vaeskf2_rcon_lsw]#least significant word of the next round key is generated by
applying a function to the most significant word of the current round key and
then XORing the result with the round constant.#
[#norm:vaeskf2_rcon_func]#The round number is used to select the round constant as well as the function.#

The round number, which [#norm:vaeskf2_uimm_src]#ranges from 2 to 14, comes from _uimm[3:0]_;
_uimm[4]_ is ignored.#
[#norm:vaeskf2_uimm_map]#The out-of-range _uimm[3:0]_ values of 0{endash}1 and 15 are mapped to in-range
values by inverting _uimm[3]_.# Thus, 0{endash}1 maps to 8{endash}9, and 15 maps to 7.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.

[NOTE]
====
We chose to map out-of-range round numbers to in-range values as this allows the instruction's
behavior to be fully defined for all values of _uimm[4:0]_ with minimal extra logic.
====

//

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
+
sail::execute[clause="VAESKF2_VI(_, _, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vaesz, Vector AES round zero]]
===== insn:vaesz.vs[]

Synopsis::
Vector AES round zero encryption/decryption

Mnemonic::
insn:vaesz.vs[vd,vs2]

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00111'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VAESZ_VS(_,_)",type=mapping,right]

Reserved Encodings::
* SEW is any value other than 32
* The _vd_ register group overlaps the _vs2_ register

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | round state
| _vs2_ | input  | 128  | 4 | 32 | round key
| _vd_  | output | 128  | 4 | 32 | new round state
|===

Description::
[#norm:vaesz_round0]#A round-0 AES block cipher operation is performed.# This operation is used for both encryption and decryption.

[#norm:vaesz_vs_only]#There is only a insn:*.vs[] form of the instruction.#
[#norm:vaesz_vs2_rk]#_vs2_ holds a
scalar element group that is used
as the round key for all of the round state element groups.#
The new round state output of each element group is produced by XORing
the round key with each element group of _vd_.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.

[NOTE]
====
This instruction is needed to avoid the need to "`splat`" a 128-bit vector register group when the round key is the same for
all 128-bit "`lanes`". Such a splat would typically be implemented with a insn:vrgather[] instruction which would hurt performance
in many implementations.
This instruction only exists in the insn:*.vs[] form because the insn:*.vv[] form would be identical to the insn:vxor.vv[vd,vs2,vd] instruction.
====

//
// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
+
sail::execute[clause="VAESZ_VS(_, _)"]

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkned[], extlink:zvkng[]

<<<

[[insns-vghsh, Vector GHASH Add-Multiply]]
===== insn:vghsh.vv[]

Synopsis::
Vector Add-Multiply over GHASH Galois-Field

Mnemonic::
insn:vghsh.vv[vd,vs2,vs1]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101100'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VGHSH_VV(_,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vghsh-vv_sewn32_rsv]#SEW is any value other than 32#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|SEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | Partial hash (Y~i~)
| _vs1_ | input  | 128  | 4 | 32 | Cipher text (X~i~)
| _vs2_ | input  | 128  | 4 | 32 | Hash Subkey (H)
| _vd_  | output | 128  | 4 | 32 | Partial-hash (Y~i+1~)
|===

Description::
A single "`iteration`" of the GHASH~H~ algorithm is performed.

[#norm:vghsh-vv_op]#This instruction treats all of the inputs and outputs as 128-bit polynomials and
performs operations over GF[2].
It produces the next partial hash (Y~i+1~) by adding the current partial
hash (Y~i~) to the cipher text block (X~i~) and then multiplying (over GF(2^128^))
this sum by the Hash Subkey (H).#

[#norm:vghsh-vv_op_gf]#The multiplication over GF(2^128^) is a carry-less multiply of two 128-bit polynomials
modulo GHASH's irreducible polynomial (x^128^ + x^7^ + x^2^ + x + 1).#

The operation can be compactly defined as
// Y~i+1~ = (Y~i~ {interpunct} H) ^ X~i~
Y~i+1~ = ((Y~i~ ^ X~i~) {interpunct} H)

[#norm:vghsh-vv_op_coeff]#The NIST specification (see extlink:zvkg[]) orders the coefficients from left to right x~0~x~1~x~2~...x~127~
for a polynomial x~0~ + x~1~u +x~2~ u^2^ + ... + x~127~u^127^. This can be viewed as a collection of
byte elements in memory with the byte containing the lowest coefficients (i.e., 0,1,2,3,4,5,6,7)
residing at the lowest memory address. Since the bits in the bytes are reversed,
this instruction internally performs bit swaps within bytes to put the bits in the standard ordering
(e.g., 7,6,5,4,3,2,1,0).#

[#norm:vghsh-vv_exeindepdata]#This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.#

[NOTE]
====
We are bit-reversing the bytes of inputs and outputs so that the intermediate values are consistent
with the NIST specification. These reversals are inexpensive to implement as they unconditionally
swap bit positions and therefore do not require any logic.
====

[NOTE]
====
Since the same hash subkey `H` will typically be used repeatedly on a given message,
a future extension might define a vector-scalar version of this instruction where
_vs2_ is the scalar element group. This would help reduce register pressure when LMUL>1.
====

Operation::
+
sail::execute[clause="VGHSH_VV(_, _, _)"]

Included in::
extlink:zvkg[], extlink:zvkng[], extlink:zvksg[]

<<<

[[insns-vgmul, Vector GHASH Multiply]]
===== insn:vgmul.vv[]

Synopsis::
Vector Multiply over GHASH Galois-Field

Mnemonic::
insn:vgmul.vv[vd,vs2]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10001'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VGMUL_VV(_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vgmul-vv_sewn32_rsv]#SEW is any value other than 32#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|SEW
|Definition

| _vd_  | input  | 128  | 4 | 32 | Multiplier
| _vs2_ | input  | 128  | 4 | 32 | Multiplicand
| _vd_  | output | 128  | 4 | 32 | Product
|===

Description::
A GHASH~H~ multiply is performed.

[#norm:vgmul-vv_op]#This instruction treats all of the inputs and outputs as 128-bit polynomials and
performs operations over GF[2].
It produces the product over GF(2^128^) of the two 128-bit inputs.#

[#norm:vgmul-vv_op_gf]#The multiplication over GF(2^128^) is a carry-less multiply of two 128-bit polynomials
modulo GHASH's irreducible polynomial (x^128^ + x^7^ + x^2^ + x + 1).#

[#norm:vgmul-vv_op_coeff]#The NIST specification (see extlink:zvkg[]) orders the coefficients from left to right x~0~x~1~x~2~...x~127~
for a polynomial x~0~ + x~1~u +x~2~ u^2^ + ... + x~127~u^127^. This can be viewed as a collection of
byte elements in memory with the byte containing the lowest coefficients (i.e., 0,1,2,3,4,5,6,7)
residing at the lowest memory address. Since the bits in the bytes are reversed,
This instruction internally performs bit swaps within bytes to put the bits in the standard ordering
(e.g., 7,6,5,4,3,2,1,0).#

[#norm:vgmul-vv_exeindepdata]#This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.#

[NOTE]
====
We are bit-reversing the bytes of inputs and outputs so that the intermediate values are consistent
with the NIST specification. These reversals are inexpensive to implement as they unconditionally
swap bit positions and therefore do not require any logic.
====

[NOTE]
====
Since the same multiplicand will typically be used repeatedly on a given message,
a future extension might define a vector-scalar version of this instruction where
_vs2_ is the scalar element group. This would help reduce register pressure when LMUL>1.
====

[NOTE]
====
This instruction is identical to insn:vghsh.vv[] with _vs1_=0.
This instruction is often used in GHASH code. In some cases it is followed
by an XOR to perform a multiply-add. Implementations may choose to fuse these
two instructions to improve performance on GHASH code that
doesn't use the add-multiply form of the insn:vghsh.vv[] instruction.
====


Operation::
+
sail::execute[clause="VGMUL_VV(_, _, _)"]

Included in::
extlink:zvkg[], extlink:zvkng[], extlink:zvksg[]

<<<

[[insns-vsha2c, Vector SHA-2 Compression]]
===== insn:vsha2ch.vv[] and insn:vsha2cl.vv[]

Synopsis::
Vector SHA-2 two rounds of compression.

Mnemonic::
insn:vsha2ch.vv[vd,vs2,vs1] +
insn:vsha2cl.vv[vd,vs2,vs1]

Encoding (Vector-Vector) High part::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101110'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="ZVKSHA2TYPE(_,_,_,_)",type=mapping,right]

where `VSHA2C.OP = ZVK_VSHA2CH_VV` and
[source,sail]
----
include::sail:encdec_vsha2[type=mapping,left-clause="ZVK_VSHA2CH_VV"]
----

Encoding (Vector-Vector) Low part::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101111'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="ZVKSHA2TYPE(_,_,_,_)",type=mapping,right]

where `VSHA2C.OP = ZVK_VSHA2CL_VV` and
[source,sail]
----
include::sail:encdec_vsha2[type=mapping,left-clause="ZVK_VSHA2CL_VV"]
----

Reserved Encodings::
* [#norm:vsha2chl-vv_Zvknha_sewn32_rsv]#ext:zvknha[]: SEW is any value other than 32#
* [#norm:vsha2chl-vv_Zvknhb_sewn32or64_rsv]#ext:zvknhb[]: SEW is any value other than 32 or 64#
* [#norm:vsha2chl-vv_vdoverlapvs1vs2_rsv]#The _vd_ register group overlaps with either _vs1_ or _vs2_#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 4*SEW  | 4 | SEW | current state {c, d, g, h}
| _vs1_ | input  | 4*SEW  | 4 | SEW | MessageSched plus constant[3:0]
| _vs2_ | input  | 4*SEW  | 4 | SEW | current state {a, b, e, f}
| _vd_  | output | 4*SEW  | 4 | SEW | next state {a, b, e, f}
|===

Description::
- [#norm:vsha2chl-vv_op_sew32]#SEW=32: 2 rounds of SHA-256 compression are performed (ext:zvknha[] and ext:zvknhb[])#
- [#norm:vsha2chl-vv_op_sew64]#SEW=64: 2 rounds of SHA-512 compression are performed (ext:zvknhb[])#

[#norm:vsha2chl-vv_op]#Two words of _vs1_ are processed with
the 8 words of current state held in _vd_ and _vs2_ to perform two
rounds of hash computation producing four words of the
next state.#


// These instructions take in two SEW words _W1_ and _W0_ which are the next two words of the message
// schedule incremented by the appropriate constant (see
// link:https://doi.org/10.6028/NIST.FIPS.180-4[FIPS PUB 180-4 Secure Hash Standard (SHS)])
// and eight SEW word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
// output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
// computation. The new values, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, // _e_, _f_ respectively.

// [NOTE]
// .Note to software developers
// ====
// The MessageSchedplus constant input to this instruction is generated by Software
// increment each message schedule word by the corresponding
// round constant as defined in the NIST specification (see extlink:zvknha[]).
// ====

[NOTE]
.Note to software developers
====
The NIST standard (see extlink:zvknha[]) requires the final hash to be in big-endian byte ordering
within SEW-sized words. Since this instruction treats all words as little-endian,
software needs to perform an endian swap on the final output of this instruction
after all of the message blocks have been processed.
====

[NOTE]
====
The insn:vsha2ch[] version of this instruction uses the two most significant message schedule
words from the element group in _vs1_
while the insn:vsha2cl[] version uses the two least significant message schedule words.
Otherwise, these versions of the instruction are identical.
Having a high and low version of this instruction typically improves performance when
interleaving independent hashing operations (i.e., when hashing several files at once).
====

// [NOTE]
// .Note to software developers
// ====
// These instructions take in two SEW words _W1_ and _W0_ which are the next two words of the message
// schedule incremented by the appropriate constant,
// and eight SEW word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
// output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
// computation. The new values, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, _e_, _f_ respectively.
// ====

// [NOTE]
// ====
// Between executions this instruction it is helpful to swap the register _specifiers_ for
// `vd` and `vs2`. This is because the first instruction's `vd` next state output
// (_a_, _b_, _e_, _f_)
// becomes the second instruction's `vs2` current state input (_a_, _b_, _e_, _f_).
// Likewise the first instruction's `vs2` input (_a_, _b_, _e_, _f_) "ages" to
// becomes the second instruction's `vd` current state input of (_c_, _d_, _g_, _h_).
// ====


[NOTE]
====
Preventing overlap between _vd_ and _vs1_ or _vs2_ simplifies implementation with VLEN<EGW.
This restriction does not have any coding impact since proper implementation of the algorithm requires
that _vd_, _vs1_ and _vs2_ each are different registers.
====



// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,sail]
--
include::sail:execute[clause="ZVKSHA2TYPE(_, _, _, _)"]
include::sail:zvk_sum0[type=val]
include::sail:zvk_sum0[]
include::sail:zvk_sum1[type=val]
include::sail:zvk_sum1[]
include::sail:zvk_ch[type=val]
include::sail:zvk_ch[]
include::sail:zvk_maj[type=val]
include::sail:zvk_maj[]
--

Included in::
extlink:zvkn[], extlink:zvknc[], extlink:zvkng[], extlink:zvknha[], extlink:zvknhb[]

<<<

[[insns-vsha2ms, Vector SHA-2 Message Schedule]]
===== insn:vsha2ms.vv[]

Synopsis::
Vector SHA-2 message schedule.

Mnemonic::
insn:vsha2ms.vv[vd,vs2,vs1]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101101'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VSHA2MS_VV(_,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vsha2ms-vv_Zvknha_sewn32_rsv]#ext:zvknha[]: SEW is any value other than 32#
* [#norm:vsha2ms-vv_Zvknhb_sewn32or64_rsv]#ext:zvknhb[]: SEW is any value other than 32 or 64#
* [#norm:vsha2ms-vv_vdoverlapvs1vs2_rsv]#The _vd_ register group overlaps with either _vs1_ or _vs2_#
Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_  | input  | 4*SEW  | 4 | SEW | Message words {W[3],  W[2],  W[1],  W[0]}
| _vs2_ | input  | 4*SEW  | 4 | SEW | Message words {W[11], W[10], W[9],  W[4]}
| _vs1_ | input  | 4*SEW  | 4 | SEW | Message words {W[15], W[14], --, W[12]}
| _vd_  | output | 4*SEW  | 4 | SEW | Message words {W[19], W[18], W[17], W[16]}
|===

Description::
- [#norm:vsha2ms-vv_op_sew32]#SEW=32: Four rounds of SHA-256 message schedule expansion are performed (ext:zvknha[] and ext:zvknhb[])#
- [#norm:vsha2ms-vv_op_sew64]#SEW=64: Four rounds of SHA-512 message schedule expansion are performed (ext:zvknhb[])#

[#norm:vsha2ms-vv_op]#Eleven of the last 16 SEW-sized message-schedule words from _vd_ (oldest), _vs2_,
and _vs1_ (most recent) are processed to produce the
next 4 message-schedule words.#

[NOTE]
.Note to software developers
====
The first 16 SEW-sized words of the message schedule come from the _message block_
in big-endian byte order. Since this instruction treats all words as little endian,
software is required to endian swap these words.

All of the subsequent message schedule words are produced by this instruction and
therefore do not require an endian swap.
====

[NOTE]
.Note to software developers
====
Software is required to pack the words into element groups
as shown above in the arguments table. The indices indicate the relate age with
lower indices indicating older words.
====
// [NOTE]
// ====
// W~13~ is not used by the instruction.
// ====

// Four `SEW` message schedule words are packed into each element group of the
// source and destination registers. From a vector register point of view,
// the message schedule words are packed into the
// element groups from the left to the right with the most significant word on the left
// and the least significant word on the right.

// `{W~3~, W~2~, W~1~, W~0~} +
// {W~7~, W~6~, W~5~, W~4~} +
// {W~11~, W~10~, W~9~, W~8~} +
// {W~15~, W~14~, W~13~, W~12~}`

// Since W~5~ through W~8~ are not needed in these calculations, we are able to compact these into
// three element groups
//
// `{W~3~, W~2~, W~1~, W~0~} +
// {W~11~, W~10~, W~9~, W~4~} +
// {W~15~, W~14~, W~13~, W~12~}`

[NOTE]
.Note to software developers
====
The {W~11~, W~10~, W~9~, W~4~} element group can easily be formed by using a vector
vmerge instruction with the appropriate mask (for example with csr:vl[]=4 and `4b0001`
as the 4 mask bits)

`vmerge.vvm {W~11~, W~10~, W~9~, W~4~}, {W~11~, W~10~, W~9~, W~8~}, {W~7~, W~6~, W~5~, W~4~}, V0`
====

// The number of words to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`

[NOTE]
====
Preventing overlap between _vd_ and _vs1_ or _vs2_ simplifies implementation with VLEN<EGW.
This restriction does not have any coding impact since proper implementation of the algorithm requires
that _vd_, _vs1_ and _vs2_ each contain different portions of the message schedule.
====

// This instruction is not masked. If any element groups are not to be processed, the _vl_
// must be set accordingly. It is not possible to skip an intermediary element group.
// `VLMUL` must be at least 1. In typical usage it is expected to be 1.
// There are three source operands: `vd`, `vs1` and `vs2`. The result
// is written to `vd`.

// NB:: for implementations with `VLEN < EGW`, the minimal `VLMUL` is `EGW / VLEN`.

// In this code the input elements are numbered from 0 (16 words ago) to 15 (most recent message-schedule word).
// The outputs are numbered from 16 to 19.

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,sail]
--
include::sail:execute[clause="VSHA2MS_VV(_, _, _)"]
include::sail:zvk_sig0[type=val]
include::sail:zvk_sig0[]
include::sail:zvk_sig1[type=val]
include::sail:zvk_sig1[]
--

Included in::
 extlink:zvkn[], extlink:zvknc[], extlink:zvkng[], extlink:zvknha[], extlink:zvknhb[]

<<<

[[insns-vsm3c, SM3 Compression]]
===== insn:vsm3c.vi[]

Synopsis::
Vector SM3 Compression

Mnemonic::
insn:vsm3c.vi[vd,vs2,uimm]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101011'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VSM3C_VI(_,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vsm3c-vi_sewn32_rsv]#SEW is any value other than 32#
* [#norm:vsm3c-vi_vdoverlapvs2_rsv]#The _vd_ register group overlaps with the _vs2_ register group#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_   | input  | 256  | 8 | 32 | Current state {H,G.F,E,D,C,B,A}
| _uimm_ | input  | -    | - | -  | round number
| _vs2_  | input  | 256  | 8 | 32 | Message words {-,-,w[5],w[4],-,-,w[1],w[0]}
| _vd_   | output | 256  | 8 | 32 | Next state {H,G.F,E,D,C,B,A}
|===

Description::
[#norm:vsm3c-vi_op]#Two rounds of SM3 compression are performed.#

[#norm:vsm3c-vi_op_sm3]#The current state of eight 32-bit words is read in as an element group from _vd_. Eight 32-bit
message words are read in as an element group from _vs2_, although only four of them are used.
All of the 32-bit input words are byte-swapped from big endian to little endian.
These inputs are processed somewhat differently based on the round group (as specified in _uimm_),
and the next state is generated as an element group of eight 32-bit words.
The next state of eight 32-bit words are generated,
swapped from little endian to big endian, and are returned in
an eight-element group.#

[#norm:vsm3c-vi_op_rnd]#The round number is provided by the 5-bit _uimm_ unsigned immediate. Legal values are 0{endash}31
and indicate which group of two rounds are being performed. For example, if _uimm_=1,
then rounds 2 and 3 are being performed.#

[NOTE]
====
The round number is used in the rotation of the constant as well to inform the
behavior which differs between rounds 0{endash}15 and rounds 16{endash}63.
====

[NOTE]
====
The endian byte swapping of the input and output words enables us to align with the SM3
specification without requiring that software perform these swaps.
====

[NOTE]
====
Preventing overlap between _vd_ and _vs2_ simplifies implementation with VLEN<EGW.
This restriction does not have any coding impact since proper implementation of the algorithm requires
that _vd_ and _vs2_ each are different registers.
====

// The elements are listed here in the order they appear in the register, with the most significant
// element on the left, and the least significant on the right.

// vs2 = {w[7], w[6], w[5], w[4], w[3], w[2], w[1], w[0]}

// The values consumed by the instruction are

// vs2 = {- , - , w[5], w[4], -, -, w[1], w[0]}

// Where the "-" characters are not consumed and are therefore don't cares.

// This instruction consumes the "W" message schedule inputs and internally generates the "W'" values as needed

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=8`. +
// Likewise, `vstart` must be a multiple of `EGS=8`.

Operation::
[source,sail]
--
include::sail:execute[clause="VSM3C_VI(_, _, _)"]
include::sail:vrev8[type=val]
include::sail:vrev8[]
include::sail:zvk_sm3_round[]
include::sail:zvk_t_j[]
include::sail:zvk_gg_j[]
include::sail:zvk_ff_j[]
include::sail:zvk_gg1[]
include::sail:zvk_gg2[]
include::sail:zvk_ff1[]
include::sail:zvk_ff2[]
include::sail:zvk_p0[]
--

Included in::
extlink:zvks[], extlink:zvksc[], extlink:zvksg[], extlink:zvksh[]

<<<

[[insns-vsm3me, SM3 Message Expansion]]
===== insn:vsm3me.vv[]

Synopsis::
Vector SM3 Message Expansion

Mnemonic::
insn:vsm3me.vv[vd,vs2,vs1]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '100000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VSM3ME_VV(_,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vsm3me-vv_sewn32_rsv]#SEW is any value other than 32#
* [#norm:vsm3me-vv_vdoverlapvs2_rsv]#The _vd_ register group overlaps with the _vs2_ register group.#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vs1_ | input  | 256  | 8 | 32 | Message words W[7:0]
| _vs2_ | input  | 256  | 8 | 32 | Message words W[15:8]
| _vd_  | output | 256  | 8 | 32 | Message words W[23:16]
|===

Description::
[#norm:vsm3me-vv_op]#Eight rounds of SM3 message expansion are performed.#


[#norm:vsm3me-vv_op_sm3]#The sixteen most recent 32-bit message words are read in as two
eight-element groups from _vs1_ and _vs2_. Each of these words is
swapped from big endian to little endian.
The next eight 32-bit message words are generated,
swapped from little endian to big endian, and are returned in
an eight-element group.#

[NOTE]
====
The endian byte swapping of the input and output words enables us to align with the SM3
specification without requiring that software perform these swaps.
====

// NOTE
// ====
// For the best performance, it is recommended that implementations have VLEN{ge}256.
// When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the
// specified register groups can be combined to form the full element group.
// ====

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=8`. +
// Likewise, `vstart` must be a multiple of `EGS=8`.

[NOTE]
====
Preventing overlap between `vd` and `vs2` simplifies implementations with `VLEN < EGW`.
This restriction should not have any coding impact since the algorithm requires these
values to be preserved for generating the next 8 words.
====

Operation::
[source,sail]
--
include::sail:execute[clause="VSM3ME_VV(_, _, _)"]
include::sail:zvk_sh_w[]
include::sail:zvk_p1[]
--

Included in::
extlink:zvks[], extlink:zvksc[], extlink:zvksg[], extlink:zvksh[]

<<<

[[insns-vsm4k, Vector SM4 Key Expansion]]
===== vsm4k.vi

Synopsis::
Vector SM4 KeyExpansion

Mnemonic::
insn:vsm4k.vi[vd,vs2,uimm]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '100001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="VSM4K_VI(_,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vsm4k-vi_sewn32_rsv]#SEW is any value other than 32#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _uimm_ | input  | -    | - | -  | Round group
| _vs2_  | input  | 128  | 4 | 32 | Current 4 round keys rK[0:3]
| _vd_   | output | 128  | 4 | 32 | Next 4 round keys rK'[0:3]
|===

Description::
[#norm:vsm4k-vi_op]#Four rounds of the SM4 Key Expansion are performed.#

[#norm:vsm4k-vi_op_sm4k]#Four round keys are read in as a 4-element group from _vs2_. Each of the next four round keys are generated
by iteratively XORing the last three round keys with a constant that is indexed by the Round Group Number,
performing a byte-wise substitution, and then performing XORs between rotated versions of this value
and the corresponding current round key.#

[#norm:vsm4k-vi_op_rnd]#The Round group number comes from _uimm[2:0]_; the bits in _uimm[4:3]_ are ignored.
Round group numbers range from 0 to 7 and indicate which
group of four round keys are being generated. Round Keys range from 0{endash}31.
For example, if _uimm_=1, then round keys 4, 5, 6, and 7 are being generated.#

//  vs2 = {rK[i-4], rK[i-3],rK[i-2], rK[i-1]} // last 4 round keys
//  rnd = 0 to 7; // group of 4 rounds
//  vd (out) = {rK[i], rK[i+1],rK[i+2], rK[i+3]} // next 4 rounds keys

// Each of the 32 rounds consumes the last 4 32-bit keys along with a round constant and
// produces the next 32-bit key.


[NOTE]
====
Software needs to generate the initial round keys. This is done by XORing the 128-bit encryption key with
the system parameters: FK[0:3]
====

.System Parameters
[%autowidth]
[%header,cols="^2,^2"]
|===
|FK
|constant

| 0 | A3B1BAC6
| 1 | 56AA3350
| 2 | 677D9197
| 3 | B27022DC
|===


////
.System Parameters
[%autowidth]
[%header,cols="^2,^2"]
|===
|FK
|constant

| 0 | A3B1BAC6
| 1 | 56AA3350
| 2 | 677D9197
| 3 | B27022DC
|===
////

//  MK = {MK[0], MK[1], MK[2], MK[3]} // Encryption Key
//  rK[-4,-1] = K[0:3] = MK[0:3] ^ FK[0:3]


// The round keys are rK[0] to rK[31]
//  B = (rK[i-3] XOR rK[i-2] XOR rK[i-1] XOR CK[round]); +
//  S = subBytes(B); +
//  rK[i]= rK[i-4] XOR S XOR ROTL13(S) XOR ROTR23(S); +
//
// The round constants and the S-box are described below and can be found at https://datatracker.ietf.org/doc/id/// draft-crypto-sm4-00

[NOTE]
====
Implementation Hint

The round constants (CK) can be generated on the fly fairly cheaply.
If the bytes of the constants are assigned an incrementing index from 0 to 127, the value of each byte is equal to its index multiplied by 7 modulo 256.
Since the results are all limited to 8 bits, the modulo operation occurs for free:

 B[n] = n + 2n + 4n;
       = 8n + ~n + 1;
====

// This instruction only returns the generated keys to the same element group as the source.
// If it is desired to have the same key in all vector groups, either the input vector groups
// need to contain the same values, or the output from a particular group needs to be "broadcast"
// to the other groups using an instruction such as vrgather.

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

////
.System Parameters
[%autowidth]
[%header,cols="^2,^2"]
|===
|FK
|constant

| 0 | A3B1BAC6
| 1 | 56AA3350
| 2 | 677D9197
| 3 | B27022DC
|===
////

Operation::
[source,sail]
--
include::sail:execute[clause="VSM4K_VI(_, _, _)"]
include::sail:zvk_round_key[]
include::sail:zvk_sm4_subword[]
include::sail:zvk_sm4_sbox[]
include::sail:zvksed_box_lookup[]
include::sail:zvksed_ck[type=let]
--

Included in::
extlink:zvks[], extlink:zvksc[], extlink:zvksed[], extlink:zvksg[]

<<<

[[insns-vsm4r, SM4 Block Cipher Rounds]]
===== insn:vsm4r.vv[] and insn:vsm4r.vs[]

Synopsis::
Vector SM4 Rounds

Mnemonic::
insn:vsm4r.vv[vd,vs2] +
insn:vsm4r.vs[vd,vs2]

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="ZVKSM4RTYPE(ZVK_VSM4R_VV,_,_)",type=mapping,right]

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-VE'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Encoding (Sail)::
include::sailwavedrom:encdec[left-clause="ZVKSM4RTYPE(ZVK_VSM4R_VS,_,_)",type=mapping,right]

Reserved Encodings::
* [#norm:vsm4r_sewn32_rsv]#SEW is any value other than 32#
* [#norm:vsm4r-vs_vdoverlapvs2_rsv]#Only for the insn:*.vs[] form: the _vd_ register group overlaps the _vs2_ register#

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| _vd_   | input  | 128  | 4 | 32 | Current state X[0:3]
| _vs2_  | input  | 128  | 4 | 32 | Round keys rk[0:3]
| _vd_   | output | 128  | 4 | 32 | Next state X'[0:3]
|===

Description::
[#norm:vsm4r_op]#Four rounds of SM4 Encryption/Decryption are performed.#

[#norm:vsm4r_op_sm4encdec]#The four words of current state are read as a 4-element group from _vd_
and the round keys are read from either the corresponding 4-element group
in _vs2_ (vector-vector form) or the scalar element group in _vs2_
(vector-scalar form).
The next four words of state are generated
by iteratively XORing the last three words of the state with
the corresponding round key, performing
a byte-wise substitution, and then performing XORs between rotated
versions of this value and the corresponding current state.#

[NOTE]
====
In SM4, encryption and decryption are identical except that decryption consumes the round keys in the reverse order.
====

[NOTE]
====
For the first  four rounds of encryption, the _current state_ is the plain text.
For the first four rounds of decryption, the _current state_ is the cipher text.
For all subsequent rounds, the _current state_ is the _next state_ from the
previous four rounds.
====

// The number of element groups to be processed is `vl`/`EGS`.
// `vl` must be set to the number of `SEW=32` elements to be processed and
// therefore must be a multiple of `EGS=4`. +
// Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,sail]
--
include::sail:execute[clause="ZVKSM4RTYPE(_, _, _)"]
include::sail:zvk_sm4_round[]
--

Included in::
extlink:zvks[], extlink:zvksc[], extlink:zvksed[], extlink:zvksg[]

<<<


[[crypto_vector_instructions]]
==== Crypto Vector Cryptographic Instructions

OP-VE (0x77)
Crypto Vector instructions

// [cols="4,1,1,1,8,4,1,1,8,4,1,1,8"]
[cols="4,1,1,1,1,4,1,1,1,4,1,1,1"]
|===
5+^|Integer 4+^|Integer 4+^| FP

| funct3 | | | |            | funct3 | | |             | funct3 | | |
| OPIVV  |V| | |            | OPMVV  |V| |             | OPFVV  |V| |
| OPIVX  | |X| |            | OPMVX  | |X|             | OPFVF  | |F|
| OPIVI  | | |I|            |        | | |             |        | | |
|===

// [cols="4,1,1,1,8,4,1,1,8,4,1,1,8"]
[cols="6,1,1,1,1,6,1,1,6,6,1,1,1"]

|===
5+^| funct6                  4+^| funct6                 4+^| funct6

|100000||||| 100000 |V| | vsm3me      | 100000 | | |
| 100001 | | | |            | 100001 |V| | vsm4k.vi    | 100001 | | |
| 100010 | | | |            | 100010 |V| | vaeskf1.vi  | 100010 | | |
| 100011 | | | |            | 100011 | | |             | 100011 | | |
| 100100 | | | |            | 100100 | | |             | 100100 | | |
| 100101 | | | |            | 100101 | | |             | 100101 | | |
| 100110 | | | |            | 100110 | | |             | 100110 | | |
| 100111 | | | |            | 100111 | | |             | 100111 | | |
|        | | | |            |        | | |             |        | | |
| 101000 | | | |            | 101000 |V| | *VAES.vv*   | 101000 | | |
| 101001 | | | |            | 101001 |V| | *VAES.vs*   | 101001 | | |
| 101010 | | | |            | 101010 |V| | vaeskf2.vi  | 101010 | | |
| 101011 | | | |            | 101011 |V| | vsm3c.vi    | 101011 | | |
| 101100 | | | |            | 101100 |V| | vghsh      | 101100 | | |
| 101101 | | | |            | 101101 |V| | vsha2ms     | 101101 | | |
| 101110 | | | |            | 101110 |V| | vsha2ch     | 101110 | | |
| 101111 | | | |            | 101111 |V| | vsha2cl     | 101111 | | |
|===

<<<

.VAES.vv and VAES.vs encoding space
[cols="2,14"]
|===
|vs1|

| 00000 | vaesdm
| 00001 | vaesdf
| 00010 | vaesem
| 00011 | vaesef
| 00111 | vaesz
| 10000 | vsm4r
| 10001 | vgmul
|===

[[crypto_vector_appx_sail]]
==== Supporting Sail Code

This section contains the supporting Sail code referenced by the
instruction descriptions throughout the specification.
The
link:https://alasdair.github.io/manual.html[Sail Manual]
is recommended reading in order to best understand the supporting code.

include::sailcomment:xt2[]

sail::xt2[part=source]

sail::xt3[part=source]

include::sailcomment:gfmul[]

sail::gfmul[part=source]

include::sailcomment:aes_mixcolumn_byte_fwd[]

sail::aes_mixcolumn_byte_fwd[part=source]

include::sailcomment:aes_mixcolumn_byte_inv[]

sail::aes_mixcolumn_byte_inv[part=source]

include::sailcomment:aes_mixcolumn_fwd[]

sail::aes_mixcolumn_fwd[part=source]

include::sailcomment:aes_mixcolumn_inv[]

sail::aes_mixcolumn_inv[part=source]

include::sailcomment:aes_decode_rcon[]

sail::aes_decode_rcon[part=source]

include::sailcomment:sm4_sbox_table_doc[type=anchor]

sail::sm4_sbox_table[type=let, part=source]

sail::aes_sbox_fwd_table[type=let, part=source]

sail::aes_sbox_inv_table[type=let, part=source]

include::sailcomment:sbox_lookup[]

sail::sbox_lookup[part=source]

include::sailcomment:aes_sbox_fwd[]

sail::aes_sbox_fwd[part=source]

include::sailcomment:aes_sbox_inv[]

sail::aes_sbox_inv[part=source]

include::sailcomment:aes_subword_fwd[]

sail::aes_subword_fwd[part=source]

include::sailcomment:aes_subword_inv[]

sail::aes_subword_inv[part=source]

include::sailcomment:sm4_sbox[]

sail::sm4_sbox[part=source]

sail::aes_get_column[part=source]

include::sailcomment:aes_apply_fwd_sbox_to_each_byte[]

sail::aes_apply_fwd_sbox_to_each_byte[part=source]

include::sailcomment:aes_apply_inv_sbox_to_each_byte[]

sail::aes_apply_inv_sbox_to_each_byte[part=source]

include::sailcomment:aes_full_round_transformations_doc[type=anchor]

sail::getbyte[part=source]

sail::aes_rv64_shiftrows_fwd[part=source]

sail::aes_rv64_shiftrows_inv[part=source]

include::sailcomment:aes_shift_rows_fwd[]

sail::aes_shift_rows_fwd[part=source]

include::sailcomment:aes_shift_rows_inv[]

sail::aes_shift_rows_inv[part=source]

include::sailcomment:aes_subbytes_fwd[]

sail::aes_subbytes_fwd[part=source]

include::sailcomment:aes_subbytes_inv[]

sail::aes_subbytes_inv[part=source]

include::sailcomment:aes_mixcolumns_fwd[]

sail::aes_mixcolumns_fwd[part=source]

include::sailcomment:aes_mixcolumns_inv[]

sail::aes_mixcolumns_inv[part=source]

sail::brev8[type=val,part=source]

sail::brev8[part=source]

sail::reverse_bits[type=val,part=source]

sail::reverse_bits[part=source]

sail::rev8[type=val,part=source]

sail::rev8[part=source]

sail::zvk_sm4_subword[part=source]
//
